name: (Prod) Build & Deploy

# Workflow triggers
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  BuildDeploySite:
    name: Build & Deploy to S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node Modules
        run: yarn install

      - name: Build Site
        run: yarn build

      - name: Configure AWS Deployment Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET }}
          aws-region: 'ap-southeast-2'
          role-to-assume: ${{ secrets.AWS_PROD_IAM_ROLE }}
          role-duration-seconds: 1200

      - name: S3 Bucket Deploy
        run: |
          if [ -z "$AWS_S3_BUCKET" ]; then
            echo "AWS_S3_BUCKET is not set. Exiting.."
            exit 1
          fi

          if [ -z "$AWS_REGION" ]; then
              echo "AWS_REGION is not set. Defaulting to ap-southeast-2."
              AWS_REGION="ap-southeast-2"
          fi

          aws s3 sync ./build s3://${AWS_S3_BUCKET}/ \
            --no-progress \
            --region ${AWS_REGION}
        env:
          AWS_S3_BUCKET: ${{ vars.S3_PROD_BUCKET }}

      - name: Create Cloudfront Invalidation
        run: |
          if [ -z "$AWS_CF_DISTRIBUTION" ]; then
            echo "AWS_CF_DISTRIBUTION is not set. Exiting.."
            exit 1
          fi

          aws cloudfront create-invalidation \
            --distribution-id ${AWS_CF_DISTRIBUTION} \
            --paths "/*"
        env:
          AWS_CF_DISTRIBUTION: ${{ vars.CF_PROD_DISTRIBUTION }}
